### ISSUE TITLE
What is the default security?

### ISSUE THREAD

**Issue by aelhadee** [justincpresley/ndn-python-svs#8]
Hello Justin, 
Is security (encryption/auth) enabled by default in the chat app? How do I change or disable it?

Thanks, 
AE

**Comment by justincpresley** [comment]
Hi AE,

```ndn-svs``` uses the default digest signature for its interest and data packets.
However, you can enable authenticate by creating [SigningInfo](https://github.com/justincpresley/ndn-python-svs/blob/enhanced/src/ndn/svs/security.py#L23) (along with ValidatingInfo) and pass that to a SecurityOptions object that is further passed to an SVS object.
You can either create HMAC, ECDSA, RSA, or Digest pub/priv key with python OR take the key/cert information from ndnsec key-gen.

For confidentiality (encryption), that is not implemented and would make for a good type. You can however encrypt the bytes (you plan to publish under a node) and then publish.

I do understand this is not as laid out as my examples, and I do have it in my plans to revisit security area of ```ndn-svs``` to make it more transparent.

Kind regards,
Justin

**Comment by aelhadee** [comment]
Great! Thanks, Justin for the clarification!
